# Generated by Django 3.0.2 on 2020-01-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightTogether', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
