# Generated by Django 3.0.2 on 2020-01-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightTogether', '0005_auto_20200113_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='love',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='politics',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refute',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
