# Generated by Django 3.0.2 on 2020-01-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightTogether', '0006_auto_20200113_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='FightTogether.Love'),
        ),
    ]
