# Generated by Django 3.0.2 on 2020-01-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FightTogether', '0008_auto_20200113_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='like_posts_refute',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='FightTogether.Refute'),
        ),
    ]
